"""VibeLight 扩展灯控协议（与固件 docs/VIBELIGHT_PROTOCOL.md 一致）。"""

from .protocol import (
    CMD_SET_BREATH_CURVE,
    CMD_SET_LIGHTING,
    CURVE_SAMPLES_MAX,
    CURVE_SAMPLES_MIN,
    FRAME_LEN,
    MAGIC,
    MODE_BREATH,
    MODE_BREATH_CURVE,
    MODE_OFF,
    MODE_SOLID,
    MODE_SYNC_BLINK,
    MASK_G,
    MASK_R,
    MASK_Y,
    PERIOD_MAX_MS,
    PERIOD_MIN_MS,
    PROTO_VER,
    build_breath_curve_frame,
    build_set_lighting_frame,
    crc8,
    parse_breath_curve_frame,
    parse_frame,
)

__all__ = [
    "MAGIC",
    "FRAME_LEN",
    "PROTO_VER",
    "CMD_SET_LIGHTING",
    "CMD_SET_BREATH_CURVE",
    "MODE_OFF",
    "MODE_SOLID",
    "MODE_SYNC_BLINK",
    "MODE_BREATH",
    "MODE_BREATH_CURVE",
    "MASK_G",
    "MASK_Y",
    "MASK_R",
    "PERIOD_MIN_MS",
    "PERIOD_MAX_MS",
    "CURVE_SAMPLES_MIN",
    "CURVE_SAMPLES_MAX",
    "crc8",
    "build_set_lighting_frame",
    "build_breath_curve_frame",
    "parse_frame",
    "parse_breath_curve_frame",
]
